# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    version-resolver: "npm_and_yarn"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    allow:
      - dependency-type: "all"
        dependency-name: "eslint"
        versions: ["^7.0.0"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: "gem"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"


